version: '3.8'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=$movies
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data

  backend:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: CDMovies
    depends_on:
      - db
    environment:
      - POSTGRES_USER=$postgres
      - POSTGRES_PASSWORD=$admin123
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/$movies
      - SPRING_DATASOURCE_USERNAME=$postgres
      - SPRING_DATASOURCE_PASSWORD=$admin123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

    ports:
      - "8080:8080"
    

volumes:
  db:
    driver: local